print('hello world', end=' ** ')
print('this is amazing!!!')
print('i am on top of the world')
print('\ni am on a new line\n\n', end='***')
print('\tsomething\ni am once again on a new line\t\t', end='this is the end')
